import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.scss";
import "@/styles/reset.scss";
import Footer from "@/widgets/footer/footer";
import Header from "@/widgets/header/header";
import Breadcrumbs from "@/entities/breadcrumbs/breadcrumbs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className}>
      <Header/>
      <Breadcrumbs/>
      <main className="main">
        {children}
      </main>

      <Footer/>
      </body>
    </html>
  );
}
